version: '3.8'
services:
  shell:
    build:
      context: .
      dockerfile: packages/host/Dockerfile
    ports:
      - "5000:80"
  dashboard:
    build:
      context: .
      dockerfile: packages/navbar/Dockerfile
    ports:
      - "5001:80"
  profile:
    build:
      context: .
      dockerfile: packages/characters/Dockerfile
    ports:
      - "5002:80"